/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.CallableStatement;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import sql.KetNoi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
/**
 *
 * @author Minh Hieu
 */
public class Menu extends javax.swing.JFrame {
    DefaultTableModel model1, model2;
    KetNoi db = new KetNoi();
    Connection con, conLSP, conSP;
    ResultSet rscb, rsLSP, rsSP;
    /**
     * Creates new form Menu
     */
    public Menu() {
        con = db.getCon();
        initComponents();
        setLocation(600, 250);
        loadcb();
        this.setLocationRelativeTo(null);
        btedit1.setEnabled(false);
        btdelete1.setEnabled(false);
        btedit2.setEnabled(false);
        btdelete2.setEnabled(false);
        model1 = (DefaultTableModel) jTable2.getModel();
        model1.setColumnIdentifiers(new Object[]{
        "STT","Mã Nhóm","Tên Nhóm"
        });
        loadLoaiSP();
        model2 = (DefaultTableModel) jTable3.getModel();
        model2.setColumnIdentifiers(new Object[]{
        "STT","Mã Sản Phẩm","Tên Sản Phẩm","Loại","Đơn Giá"
        });
        loadSP();
    }
    void close(){
        WindowEvent closewd = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closewd);
    }
    int i = 1;
    public void loadLoaiSP(){
        try {
            conLSP = db.getCon();
            String sql = "select * from Loai";
            PreparedStatement psLSP = conLSP.prepareStatement(sql);
            rsLSP = psLSP.executeQuery();
            while (rsLSP.next()) {
               Vector rowLSP = new Vector();
                rowLSP.add(i++);
                rowLSP.add(rsLSP.getString("maloai"));
                rowLSP.add(rsLSP.getString("tenloai"));
                model1.addRow(rowLSP);
            }
            jTable2.setModel(model1);
            jTable2.setDefaultEditor(Object.class, null);//k cho chỉnh sửa jtable
        } catch (Exception e) {
        }
    }
    public void loadSP(){
        int j = 1;
        try{
            conSP = db.getCon();
            String sql1 = "select * from ThucDon inner join Loai on ThucDon.maloai=Loai.maloai";
            PreparedStatement psSP = conSP.prepareStatement(sql1);
            rsSP = psSP.executeQuery();
            while(rsSP.next()){
                Vector rowSP = new Vector();
                rowSP.add(j++);
                rowSP.add(rsSP.getString("MaMon"));
                rowSP.add(rsSP.getString("TenMon"));
                rowSP.add(rsSP.getString("tenloai"));
               rowSP.add(rsSP.getString("DonGia"));
               model2.addRow(rowSP);
            }
            jTable3.setModel(model2);
            jTable3.setDefaultEditor(Object.class, null);
        }catch(Exception e){JOptionPane.showMessageDialog(null, "Lỗi");}
        
    }
    public void loadcb(){
    try{
            Statement st = con.createStatement();
        String sql = "SELECT tenloai FROM Loai";
        rscb = st.executeQuery(sql);
            while(rscb.next()){
                String s = rscb.getString(1);
                cbloai.addItem(s);
            }
        }catch (Exception e){}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtidnsp = new javax.swing.JTextField();
        txttennsp = new javax.swing.JTextField();
        btadd1 = new javax.swing.JButton();
        btedit1 = new javax.swing.JButton();
        btdelete1 = new javax.swing.JButton();
        btreset1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtidsp = new javax.swing.JTextField();
        txttensp = new javax.swing.JTextField();
        txtdongia = new javax.swing.JTextField();
        cbloai = new javax.swing.JComboBox<>();
        btadd2 = new javax.swing.JButton();
        btedit2 = new javax.swing.JButton();
        btdelete2 = new javax.swing.JButton();
        btrset2 = new javax.swing.JButton();
        btfind = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable2MouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 138, 393, 221));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("ID Nhóm SP:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 35, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Tên Nhóm SP:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 73, -1, -1));
        jPanel1.add(txtidnsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 33, 139, -1));
        jPanel1.add(txttennsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 71, 139, -1));

        btadd1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btadd1.setForeground(new java.awt.Color(51, 255, 51));
        btadd1.setText("Thêm");
        btadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btadd1ActionPerformed(evt);
            }
        });
        jPanel1.add(btadd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 97, 73, -1));

        btedit1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btedit1.setForeground(new java.awt.Color(255, 153, 0));
        btedit1.setText("Sửa");
        btedit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btedit1ActionPerformed(evt);
            }
        });
        jPanel1.add(btedit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 97, 73, -1));

        btdelete1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btdelete1.setForeground(new java.awt.Color(255, 0, 0));
        btdelete1.setText("Xóa");
        btdelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdelete1ActionPerformed(evt);
            }
        });
        jPanel1.add(btdelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 97, 73, -1));

        btreset1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btreset1.setForeground(new java.awt.Color(153, 0, 153));
        btreset1.setText("Làm mới");
        btreset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btreset1ActionPerformed(evt);
            }
        });
        jPanel1.add(btreset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 97, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/im/anh-nen-mau-xam_055858999.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 670, 370));

        jTabbedPane1.addTab("Cập Nhật Nhóm Sản Phẩm", jPanel1);

        jPanel2.setForeground(new java.awt.Color(153, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 174, 550, 190));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ID Sản Phẩm:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 13, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tên Sản Phẩm:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 44, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nhóm:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 73, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Đơn Giá:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));
        jPanel2.add(txtidsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 11, 122, -1));
        jPanel2.add(txttensp, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 42, 122, -1));
        jPanel2.add(txtdongia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 122, -1));

        jPanel2.add(cbloai, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 74, 122, -1));

        btadd2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btadd2.setForeground(new java.awt.Color(51, 225, 51));
        btadd2.setText("Thêm");
        btadd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btadd2ActionPerformed(evt);
            }
        });
        jPanel2.add(btadd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 138, 73, 30));

        btedit2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btedit2.setForeground(new java.awt.Color(255, 153, 0));
        btedit2.setText("Sửa");
        btedit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btedit2ActionPerformed(evt);
            }
        });
        jPanel2.add(btedit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 145, 73, -1));

        btdelete2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btdelete2.setForeground(new java.awt.Color(255, 0, 0));
        btdelete2.setText("Xóa");
        btdelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdelete2ActionPerformed(evt);
            }
        });
        jPanel2.add(btdelete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 145, 73, -1));

        btrset2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btrset2.setForeground(new java.awt.Color(153, 0, 153));
        btrset2.setText("Làm Mới");
        btrset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrset2ActionPerformed(evt);
            }
        });
        jPanel2.add(btrset2, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 145, -1, -1));

        btfind.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btfind.setText("Tìm Kiếm");
        btfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfindActionPerformed(evt);
            }
        });
        jPanel2.add(btfind, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/im/anh-nen-mau-xam_055858999.jpg"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 670, 370));

        jTabbedPane1.addTab("Cập Nhập Sản Phẩm", jPanel2);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/im/MENU.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(53, 53, 53)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        close();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btreset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btreset1ActionPerformed
        txtidnsp.setEnabled(true);
        btedit1.setEnabled(false);
        btdelete1.setEnabled(false);
        btadd1.setEnabled(true);
        txtidnsp.setText("");
        txttennsp.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btreset1ActionPerformed

    private void btrset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrset2ActionPerformed
        btedit2.setEnabled(false);
        btdelete2.setEnabled(false);
        btadd2.setEnabled(true);
        txtidsp.setText("");
        txttensp.setText("");
        txtdongia.setText("");
        cbloai.setSelectedIndex(-1);
        model2.setRowCount(0);
        loadSP();// TODO add your handling code here:
    }//GEN-LAST:event_btrset2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        txtidnsp.setEnabled(false);
        btedit1.setEnabled(true);
        btdelete1.setEnabled(true);
        btadd1.setEnabled(false);
        int selectedRowIndex = jTable2.getSelectedRow();
        txtidnsp.setText(model1.getValueAt(selectedRowIndex, 1).toString());
        txttennsp.setText(model1.getValueAt(selectedRowIndex, 2).toString());// click để nhận kết quả jtextfied
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        btedit2.setEnabled(true);
        btdelete2.setEnabled(true);
        btadd2.setEnabled(false);
        int selec = jTable3.getSelectedRow();
        txtidsp.setText(model2.getValueAt(selec, 1).toString());
        txttensp.setText(model2.getValueAt(selec, 2).toString());
        cbloai.setSelectedItem(model2.getValueAt(selec, 3));
        txtdongia.setText(model2.getValueAt(selec, 4).toString());// TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void btfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfindActionPerformed
      if(cbloai.getSelectedIndex() == -1){
          JOptionPane.showMessageDialog(null, "Không để trống");
      }else{
          int i =1;
          model2.setRowCount(0);
          Connection con = db.getCon();
          try{
              String sl = "{call spfind1 (?)}";
              CallableStatement ps = con.prepareCall(sl);
              ps.setString(1, (String) cbloai.getSelectedItem());
              ps.execute();
              ResultSet rs = ps.getResultSet();
              while(rs.next()){
                  Vector vv = new Vector();
                  vv.add(i++);
                  vv.add(rs.getString("MaMon"));
                  vv.add(rs.getString("TenMon"));
                  vv.add(rs.getString("tenloai"));
                  vv.add(rs.getString("DonGia"));
                  model2.addRow(vv);
              }
              jTable3.setModel(model2);
          }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
      }
    }//GEN-LAST:event_btfindActionPerformed

    private void btadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btadd1ActionPerformed
        int line = jTable2.getRowCount();
        if(txtidnsp.getText().equals("") || txttennsp.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Có hàng rỗng");
            return;
        }else{
              while(true){
                  for(int i = 0; i<line; i++){
                      if(txtidnsp.getText().trim().equals(jTable2.getValueAt(i, 1))){
                          JOptionPane.showMessageDialog(null, "ID trùng");
                          return;
                      }
                  }
                  if(!txtidnsp.getText().trim().matches("[A-Z]{3}[0-9]{3}")){
                      JOptionPane.showMessageDialog(null, "ID= 3 từ in + 3 số");
                      return;
                  }else break;
              }  
        }
        try{
            String sql = "insert into Loai values(?,?)";
            PreparedStatement psLSP = conLSP.prepareStatement(sql);
            psLSP.setString(1, txtidnsp.getText());
            psLSP.setString(2, txttennsp.getText());
            psLSP.executeUpdate();
            model1.setRowCount(0);
            loadLoaiSP();
            JOptionPane.showMessageDialog(null, "Thêm thành công");
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_btadd1ActionPerformed

    private void btdelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdelete1ActionPerformed
        String xoa = "select * from Loai where maloai=?";
        try{
        PreparedStatement psx = conLSP.prepareStatement(xoa);
        psx.setString(1, txtidnsp.getText());
        rsLSP = psx.executeQuery();
        if(rsLSP.next()){
            int click = JOptionPane.showConfirmDialog(null, "Bạn muốn xóa?");
            if(click == 0){
                try{
                psx = conLSP.prepareStatement("delete Loai where maloai=?");
                psx.setString(1, txtidnsp.getText());
                psx.executeUpdate();
                model1.setRowCount(0);
                loadLoaiSP();
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                }catch(Exception e){JOptionPane.showMessageDialog(null, "Có liên kết với giá trị khác không thể xóa");}
            }else JOptionPane.showMessageDialog(null, "Xóa không thành công");
        }
        }catch(Exception e){}
    }//GEN-LAST:event_btdelete1ActionPerformed

    private void btedit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btedit1ActionPerformed

        if(txtidnsp.getText().equals("") || txttennsp.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Có hàng rỗng");
            return;
        }
        try{
            String sql = "update Loai set tenloai=? where maloai=?";
            PreparedStatement psu = conLSP.prepareStatement(sql);
            psu.setString(1, txttennsp.getText());
            psu.setString(2, txtidnsp.getText());
            psu.executeUpdate();
            model1.setRowCount(0);
            loadLoaiSP();
            JOptionPane.showMessageDialog(null, "Sửa thành công");
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_btedit1ActionPerformed

    private void jTable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseEntered

    private void btadd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btadd2ActionPerformed
        int line = jTable3.getRowCount();
        if(txtidsp.getText().equals("") || txttensp.getText().equals("") || txtdongia.getText().equals("") || cbloai.getSelectedIndex()== -1){
            JOptionPane.showMessageDialog(null, "Có hàng để trống");
            return;
        }else{
            while(true){
                for(int i = 0; i<line; i++){
                if(txtidsp.getText().equals(jTable3.getValueAt(i, 1))){
                    JOptionPane.showMessageDialog(null, "ID trùng");
                    return;
                }
                }
                if(!txtidsp.getText().trim().matches("[A-Z]{2}[0-9]{4}")){
                    JOptionPane.showMessageDialog(null, "ID= 2 từ IN hoa + 4 số");
                    return;
                }
                try{
                    int e = Integer.parseInt(txtdongia.getText());
                }catch(Exception e){JOptionPane.showMessageDialog(null, "Nhập giá trị số"); return;}
                if(Integer.parseInt(txtdongia.getText()) <0){
                    JOptionPane.showMessageDialog(null, "Đơn giá phải lớn hơn 0");
                    return;
                }else break;
            }
        }
        try{
        String id = null;
        while(true){
            String sql2 = "select * from Loai where tenloai=?";
            PreparedStatement psSP = conSP.prepareStatement(sql2);
            psSP.setString(1, cbloai.getSelectedItem().toString());
            rsSP = psSP.executeQuery();
            if(rsSP.next()){
                id = rsSP.getString(1);
                break;
            }else break;
        }
            String sqlq = "insert into ThucDon values(?,?,?,?)";
            PreparedStatement psin = conSP.prepareStatement(sqlq);
            psin.setString(1, txtidsp.getText());
            psin.setString(2, txttensp.getText());
            psin.setString(3, id);
            psin.setInt(4, Integer.parseInt(txtdongia.getText()));
            psin.executeUpdate();
            model2.setRowCount(0);
            loadSP();
            JOptionPane.showMessageDialog(null, "Thêm thành công");
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_btadd2ActionPerformed

    private void btdelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdelete2ActionPerformed
        String xoa = "select * from ThucDon where MaMon=?";
        try{
            PreparedStatement psSP = conSP.prepareStatement(xoa);
            psSP.setString(1, txtidsp.getText());
            rsSP = psSP.executeQuery();
            if(rsSP.next()){
                int click = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không?");
                if(click == 0){
                    try{
                        String sql = "delete ThucDon where MaMon=?";
                        PreparedStatement psde = conSP.prepareStatement(sql);
                        psde.setString(1, txtidsp.getText());
                        psde.executeUpdate();
                        model2.setRowCount(0);
                        loadSP();
                        btedit2.setEnabled(false);
                        btdelete2.setEnabled(false);
                        btadd2.setEnabled(true);
                        txtidsp.setText("");
                        txttensp.setText("");
                        txtdongia.setText("");
                        cbloai.setSelectedIndex(-1);
                        JOptionPane.showMessageDialog(null, "Xóa thành công");
                    }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
                }else JOptionPane.showMessageDialog(null, "Xóa không thành công");
            }
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
        
    }//GEN-LAST:event_btdelete2ActionPerformed

    private void btedit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btedit2ActionPerformed

        if(txtidsp.getText().equals("") || txttensp.getText().equals("") || txtdongia.getText().equals("") || cbloai.getSelectedIndex()== -1){
            JOptionPane.showMessageDialog(null, "Có hàng để trống");
            return;
        }else{
            while(true){
                try{
                    int k = Integer.parseInt(txtdongia.getText());
                }catch(Exception e){JOptionPane.showMessageDialog(null, "Nhập giá trị số"); return;}
                if(Integer.parseInt(txtdongia.getText()) <0){
                    JOptionPane.showMessageDialog(null, "Đơn giá phải lớn hơn 0");
                    return;
                }else break;
            }
        }
        try{
        String id = null;
        while(true){
            String sql2 = "select * from Loai where tenloai=?";
            PreparedStatement psSP = conSP.prepareStatement(sql2);
            psSP.setString(1, cbloai.getSelectedItem().toString());
            rsSP = psSP.executeQuery();
            if(rsSP.next()){
                id = rsSP.getString(1);
                break;
            }else break;
        }
            String sqlq = "update ThucDon set TenMon=?, maloai=?, DonGia=? where MaMon=?";
            PreparedStatement psup = conSP.prepareStatement(sqlq);
            psup.setString(1, txttensp.getText());
            psup.setString(2, id);
            psup.setInt(3, Integer.parseInt(txtdongia.getText()));
            psup.setString(4, txtidsp.getText());
            psup.executeUpdate();
            model2.setRowCount(0);
            loadSP();
            JOptionPane.showMessageDialog(null, "Sửa thành công");
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_btedit2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd1;
    private javax.swing.JButton btadd2;
    private javax.swing.JButton btdelete1;
    private javax.swing.JButton btdelete2;
    private javax.swing.JButton btedit1;
    private javax.swing.JButton btedit2;
    private javax.swing.JButton btfind;
    private javax.swing.JButton btreset1;
    private javax.swing.JButton btrset2;
    private javax.swing.JComboBox<String> cbloai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField txtdongia;
    private javax.swing.JTextField txtidnsp;
    private javax.swing.JTextField txtidsp;
    private javax.swing.JTextField txttennsp;
    private javax.swing.JTextField txttensp;
    // End of variables declaration//GEN-END:variables
}
