/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.Vector;
import javax.swing.JOptionPane;
import sql.KetNoi;
import java.sql.*;
import java.util.*;
import java.sql.CallableStatement;
import java.text.DateFormat;
/*
 * @author Minh Hieu
 */
public class whouse extends javax.swing.JFrame {
    DefaultTableModel model;
    KetNoi db = new KetNoi();
    Connection con;
    ResultSet rs;
    PreparedStatement ps;
    /**
     * Creates new form whouse
     */
    public whouse() {
        con = db.getCon();
        initComponents();
        setLocation(550, 250);
        dcngay.setDateFormatString("dd/MM/yyyy");
        btdelete.setEnabled(false);
        btedit.setEnabled(false);
        model = (DefaultTableModel) jTable1.getModel();
        model.setColumnIdentifiers(new Object[]{
            "STT","ID Đơn Hàng","Tên Đơn Hàng","Số Lượng","Đơn Vị","Đơn Giá","Ngày Nhập"
        });
        LoadKho();
    }
    public void close(){
        WindowEvent closed = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closed);
    }
    public void LoadKho(){
        int i = 1;
    try{
        String sql = "select * from Kho";
        ps = con.prepareStatement(sql);
        rs = ps.executeQuery();
        while(rs.next()){
            Vector row = new Vector();
            row.add(i++);
            row.add(rs.getString("maKH"));
            row.add(rs.getString("tenKH"));
            row.add(rs.getString("soluong"));
            row.add(rs.getString("DVT"));
            row.add(rs.getString("dongia"));
            row.add(rs.getString("ngaynhap"));
            model.addRow(row);
        }
        jTable1.setModel(model);
        jTable1.setDefaultEditor(Object.class, null);
    }catch(Exception e){JOptionPane.showMessageDialog(null, "Lỗi");}
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtiddonhang = new javax.swing.JTextField();
        txttendonhang = new javax.swing.JTextField();
        txtDVT = new javax.swing.JTextField();
        txtdongiak = new javax.swing.JTextField();
        btkfind = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        btreset = new javax.swing.JButton();
        btadd = new javax.swing.JButton();
        dcngay = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtsoluong1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImages(getIconImages());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 73, -1));

        jLabel1.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Kho Hàng");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 220, 39));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 561, 181));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Tên đơn hàng:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 97, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Số lượng:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 128, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Đơn Giá:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setText("Ngày Nhập:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setText("ID Đơn hàng:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 65, -1, -1));

        txtiddonhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtiddonhangActionPerformed(evt);
            }
        });
        getContentPane().add(txtiddonhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 63, 113, -1));
        getContentPane().add(txttendonhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 95, 113, -1));
        getContentPane().add(txtDVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 113, -1));
        getContentPane().add(txtdongiak, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 113, -1));

        btkfind.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btkfind.setText("Tìm Kiếm");
        btkfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkfindActionPerformed(evt);
            }
        });
        getContentPane().add(btkfind, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        btedit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btedit.setForeground(new java.awt.Color(255, 153, 0));
        btedit.setText("Sửa");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });
        getContentPane().add(btedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 95, 73, -1));

        btdelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btdelete.setForeground(new java.awt.Color(255, 0, 0));
        btdelete.setText("Xoá");
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 129, 73, -1));

        btreset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btreset.setForeground(new java.awt.Color(153, 0, 153));
        btreset.setText("Làm mới");
        btreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresetActionPerformed(evt);
            }
        });
        getContentPane().add(btreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        btadd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btadd.setForeground(new java.awt.Color(51, 255, 51));
        btadd.setText("Thêm");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });
        getContentPane().add(btadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 61, 73, -1));
        getContentPane().add(dcngay, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 192, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("Đơn Vị:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        getContentPane().add(txtsoluong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 126, 113, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/im/anh-nen-mau-xam_055858999.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 0, 590, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        close(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        txtiddonhang.setEnabled(true);
        btkfind.setEnabled(true);
        btedit.setEnabled(false);
        btdelete.setEnabled(false);
        btadd.setEnabled(true);
        txtiddonhang.setText("");
        txttendonhang.setText("");
        txtDVT.setText("");
        txtsoluong1.setText("");
        txtdongiak.setText("");
        dcngay.setDate(null);
        model.setRowCount(0);
        LoadKho();
        //dcnhap.set// TODO add your handling code here:
    }//GEN-LAST:event_btresetActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        txtiddonhang.setEnabled(false);
        btkfind.setEnabled(false);
        btedit.setEnabled(true);
        btdelete.setEnabled(true);
        btadd.setEnabled(false);
        int selec = jTable1.getSelectedRow();
        txtiddonhang.setText(jTable1.getValueAt(selec, 1).toString());
        txttendonhang.setText(jTable1.getValueAt(selec, 2).toString());
        txtsoluong1.setText(jTable1.getValueAt(selec, 3).toString());
        txtDVT.setText(jTable1.getValueAt(selec, 4).toString());
        txtdongiak.setText(jTable1.getValueAt(selec, 5).toString());
        try{
        Date date = new SimpleDateFormat("dd/MM/yyyy").parse((String)model.getValueAt(selec, 6).toString());
        dcngay.setDate(date);
        }catch(Exception e){JOptionPane.showMessageDialog(null, "lỗi");}// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void btkfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkfindActionPerformed

        SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault());
            int i = 1;
            Connection conf = db.getCon();
            try{
                String ss = "{call kfind (?)}";
                CallableStatement psk = conf.prepareCall(ss);
                psk.setString(1, date.format(dcngay.getDate()));
                psk.execute();
                ResultSet rsk = psk.getResultSet();
                model.setRowCount(0);
                while(rsk.next()){
                    Vector to = new Vector();
                    to.add(i++);
                    to.add(rsk.getString("maKH"));
                    to.add(rsk.getString("tenKH"));
                    to.add(rsk.getString("soluong"));
                    to.add(rsk.getString("DVT"));
                    to.add(rsk.getString("dongia"));
                    to.add(rsk.getString("ngaynhap"));
                    model.addRow(to);
                }
                jTable1.setModel(model);
            }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
        
    }//GEN-LAST:event_btkfindActionPerformed

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
    
        int line = jTable1.getRowCount();
        try{
        }catch(Exception e){JOptionPane.showMessageDialog(null, "Ngày rỗng"); return;}
        if(txtiddonhang.getText().equals("") || txttendonhang.getText().equals("") || txtDVT.getText().equals("") || txtdongiak.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Có Hàng để trống");
        }else{
            try{
                while(true){
                    for(int i = 0; i< line; i++){
                        String s = (String) jTable1.getValueAt(i, 1);
                        if(txtiddonhang.getText().trim().equals(s)){
                            JOptionPane.showMessageDialog(null, "ID Trùng");
                            return;
                        }
                    }
                    if(!txtiddonhang.getText().trim().matches("KH[0-9]{4}")){
                        JOptionPane.showMessageDialog(null, "ID: KH + 4 chữ só ");
                        return;
                    }
                    int dv = Integer.parseInt(txtsoluong1.getText());
                    if(dv<0){
                        JOptionPane.showMessageDialog(null, "số lượng phải lớn hơn 1");
                        return;
                    }
                    if(Integer.parseInt(txtdongiak.getText()) < 0){
                        JOptionPane.showMessageDialog(null, "Đơn giá phải lớn 0");
                        return;
                    }else break;
                }
                SimpleDateFormat date1 = new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault());
                try{
                Connection connk = db.getCon();
                String sqll = "insert into Kho values(?,?,?,?,?,?)";
                PreparedStatement psnk = connk.prepareStatement(sqll);
                psnk.setString(1, txtiddonhang.getText());
                psnk.setString(2, txttendonhang.getText());
                psnk.setInt(3, Integer.parseInt(txtsoluong1.getText()));
                psnk.setString(4, txtDVT.getText());
                psnk.setInt(5, Integer.parseInt(txtdongiak.getText()));
                psnk.setString(6, date1.format(dcngay.getDate()));
                psnk.executeUpdate();
                model.setRowCount(0);
                LoadKho();
                JOptionPane.showMessageDialog(null, "Thêm thành công");
                }catch(Exception e ){JOptionPane.showMessageDialog(null, "Lỗi");}
            }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
        }
    }//GEN-LAST:event_btaddActionPerformed

    private void txtiddonhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtiddonhangActionPerformed

    }//GEN-LAST:event_txtiddonhangActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed

        try{
        }catch(Exception e){JOptionPane.showMessageDialog(null, "Ngày rỗng"); return;}
        if(txtiddonhang.getText().equals("") || txttendonhang.getText().equals("") || txtDVT.getText().equals("") || txtdongiak.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Có Hàng để trống");
        }else{
                while(true){
                    if(!txtiddonhang.getText().trim().matches("KH[0-9]{4}")){
                        JOptionPane.showMessageDialog(null, "ID: KH + 4 chữ só ");
                        return;
                    }
                    int dv = Integer.parseInt(txtsoluong1.getText());
                    if(dv<0){
                        JOptionPane.showMessageDialog(null, "số lượng phải lớn hơn 1");
                        return;
                    }
                    if(Integer.parseInt(txtdongiak.getText()) < 0){
                        JOptionPane.showMessageDialog(null, "Đơn giá phải lớn 0");
                        return;
                    }else break;
                }}
        SimpleDateFormat date2 = new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault());
        try{
           String sup = "update Kho set tenKH=?, soluong=?, DVT=?, dongia=?, ngaynhap=? where maKH=?";
           ps = con.prepareStatement(sup);
           ps.setString(1, txttendonhang.getText());
           ps.setInt(2, Integer.parseInt(txtsoluong1.getText()));
           ps.setString(3, txtDVT.getText());
           ps.setInt(4, Integer.parseInt(txtdongiak.getText()));
           ps.setString(5, date2.format(dcngay.getDate()));
           ps.setString(6, txtiddonhang.getText());
           ps.executeUpdate();
           model.setRowCount(0);
           LoadKho();
           JOptionPane.showMessageDialog(null, "Sửa thành công");
       }catch (Exception e){JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_bteditActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
       String xoa = "select * from Kho where maKH=?";
       try{
       ps = con.prepareStatement(xoa);
       ps.setString(1, txtiddonhang.getText());
       rs = ps.executeQuery();
       if(rs.next()){
           int click = JOptionPane.showConfirmDialog(null, "Bạn muốn xóa ?");
           if(click == 0){
               try{
                   String sql = "delete Kho where maKH=?";
                   ps = con.prepareStatement(sql);
                   ps.setString(1, txtiddonhang.getText());
                   ps.executeUpdate();
                   model.setRowCount(0);
                   LoadKho();
                   JOptionPane.showMessageDialog(null, "Xóa thành công");
               }catch(Exception e){}
       }else JOptionPane.showMessageDialog(null, "Xóa không thành công");
       }else JOptionPane.showMessageDialog(null, "Sản phẩm Không tồn tại");
       }catch(Exception e){}
    }//GEN-LAST:event_btdeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(whouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(whouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(whouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(whouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new whouse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btedit;
    private javax.swing.JButton btkfind;
    private javax.swing.JButton btreset;
    private com.toedter.calendar.JDateChooser dcngay;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDVT;
    private javax.swing.JTextField txtdongiak;
    private javax.swing.JTextField txtiddonhang;
    private javax.swing.JTextField txtsoluong1;
    private javax.swing.JTextField txttendonhang;
    // End of variables declaration//GEN-END:variables
}
